# Generated by Django 3.2.2 on 2021-05-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
